### ISSUE TITLE
Question: Data Protection

### ISSUE THREAD

**Issue by 0xj0n1** [zxy19/flarum-collector#1]
Is it even legal to collect this type of data? What exactly is being collected?
Greetings,
Joni

**Comment by zxy19** [comment]
For second question, this extension collects data just as auto-moderator did. And the difference is our extension cache the data in database. You can view a list in admin panel and be free disabling any data.

As for legality, actually, I don't think it's a problem because the data we collect has already exist in database which was created by other extension. 

I'v notice a extension called flarum/gdpr that enables user deleting their data. If is needed, I'll try to make this extension compatible with it.

**Comment by 0xj0n1** [comment]
Ok that would be great 👍🏽
